In [38]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import os

In [39]:
dataset = os.path.join('datasets', 'smartphones.csv')
df = pd.read_csv(dataset)
df

                Name        OS  Capacity  Ram  Weight    Company  inch
0         Galaxy S10   Android       128    8   163.0    Samsung   6.2
1          Lumia 950  windows         32    3   150.0  Microsoft   5.2
2        Xpreia 1 ll   Android       256    8   181.0       Sony   6.5
3          iphone 7        ios       128    2   138.0      Apple   4.7
4            U Ultra   Android        64    4   170.0        HTC   5.7
5          Galaxy S5   Android        16    2   145.0    Samsung   5.1
6  iphone 11 pro max       ios       256    4   226.0      Apple   6.5
7            Moto G5   Android        16    3   144.5   Motorola   5.0
8             Pixel    Android       128    4   143.0     Google   5.0

In [40]:
df.set_index('Name', inplace=True)
df

                         OS  Capacity  Ram  Weight    Company  inch
Name
Galaxy S10          Android       128    8   163.0    Samsung   6.2
Lumia 950          windows         32    3   150.0  Microsoft   5.2
Xpreia 1 ll         Android       256    8   181.0       Sony   6.5
iphone 7                ios       128    2   138.0      Apple   4.7
U Ultra             Android        64    4   170.0        HTC   5.7
Galaxy S5           Android        16    2   145.0    Samsung   5.1
iphone 11 pro max       ios       256    4   226.0      Apple   6.5
Moto G5             Android        16    3   144.5   Motorola   5.0
Pixel               Android       128    4   143.0     Google   5.0

In [41]:
df.drop('Company', axis=1, inplace=True)
df

                         OS  Capacity  Ram  Weight  inch
Name
Galaxy S10          Android       128    8   163.0   6.2
Lumia 950          windows         32    3   150.0   5.2
Xpreia 1 ll         Android       256    8   181.0   6.5
iphone 7                ios       128    2   138.0   4.7
U Ultra             Android        64    4   170.0   5.7
Galaxy S5           Android        16    2   145.0   5.1
iphone 11 pro max       ios       256    4   226.0   6.5
Moto G5             Android        16    3   144.5   5.0
Pixel               Android       128    4   143.0   5.0

In [42]:
df_dummies = pd.get_dummies(df)
df_dummies

,Capacity,Ram,Weight,inch,OS_Android,OS_ios,OS_windows
Name,,,,,,,
Galaxy S10,128,8,163.0,6.2,True,False,False
Lumia 950,32,3,150.0,5.2,False,False,True
Xpreia 1 ll,256,8,181.0,6.5,True,False,False
iphone 7,128,2,138.0,4.7,False,True,False
U Ultra,64,4,170.0,5.7,True,False,False
Galaxy S5,16,2,145.0,5.1,True,False,False
iphone 11 pro max,256,4,226.0,6.5,False,True,False
Moto G5,16,3,144.5,5.0,True,False,False
Pixel,128,4,143.0,5.0,True,False,False

In [43]:
from sklearn.preprocessing import scale

In [44]:
scale_data = scale(df_dummies)
scale_data

array([[ 0.16202168,  1.75809815,  0.02752212,  0.99557678,  0.70710678,
        -0.53452248, -0.35355339],
       [-0.93162467, -0.56879646, -0.46787604, -0.52309966, -1.41421356,
        -0.53452248,  2.82842712],
       [ 1.62021682,  1.75809815,  0.71345804,  1.45117971,  0.70710678,
        -0.53452248, -0.35355339],
       [ 0.16202168, -1.03417538, -0.92516666, -1.28243788, -1.41421356,
         1.87082869, -0.35355339],
       [-0.56707589, -0.10341754,  0.29427498,  0.23623856,  0.70710678,
        -0.53452248, -0.35355339],
       [-1.11389906, -1.03417538, -0.6584138 , -0.67496731,  0.70710678,
        -0.53452248, -0.35355339],
       [ 1.62021682, -0.10341754,  2.42829784,  1.45117971, -1.41421356,
         1.87082869, -0.35355339],
       [-1.11389906, -0.56879646, -0.67746757, -0.82683495,  0.70710678,
        -0.53452248, -0.35355339],
       [ 0.16202168, -0.10341754, -0.7346289 , -0.82683495,  0.70710678,
        -0.53452248, -0.35355339]])

In [46]:
df_scaled = pd.DataFrame(scale_data, index=df_dummies.index, columns=df_dummies.columns)
df_scaled

,Capacity,Ram,Weight,inch,OS_Android,OS_ios,OS_windows
Name,,,,,,,
Galaxy S10,0.162022,1.758098,0.027522,0.995577,0.707107,-0.534522,-0.353553
Lumia 950,-0.931625,-0.568796,-0.467876,-0.523100,-1.414214,-0.534522,2.828427
Xpreia 1 ll,1.620217,1.758098,0.713458,1.451180,0.707107,-0.534522,-0.353553
iphone 7,0.162022,-1.034175,-0.925167,-1.282438,-1.414214,1.870829,-0.353553
U Ultra,-0.567076,-0.103418,0.294275,0.236239,0.707107,-0.534522,-0.353553
Galaxy S5,-1.113899,-1.034175,-0.658414,-0.674967,0.707107,-0.534522,-0.353553
iphone 11 pro max,1.620217,-0.103418,2.428298,1.451180,-1.414214,1.870829,-0.353553
Moto G5,-1.113899,-0.568796,-0.677468,-0.826835,0.707107,-0.534522,-0.353553
Pixel,0.162022,-0.103418,-0.734629,-0.826835,0.707107,-0.534522,-0.353553

In [47]:
from sklearn.preprocessing import normalize

In [50]:
norm_data = normalize(df_dummies, norm='l2', axis=0)
norm_data

array([[0.29690785, 0.56287804, 0.33052326, 0.37014431, 0.40824829,
        0.        , 0.        ],
       [0.07422696, 0.21107926, 0.30416251, 0.31044361, 0.        ,
        0.        , 1.        ],
       [0.5938157 , 0.56287804, 0.36702276, 0.38805451, 0.40824829,
        0.        , 0.        ],
       [0.29690785, 0.14071951, 0.27982951, 0.28059326, 0.        ,
        0.70710678, 0.        ],
       [0.14845392, 0.28143902, 0.34471751, 0.34029396, 0.40824829,
        0.        , 0.        ],
       [0.03711348, 0.14071951, 0.29402376, 0.30447354, 0.40824829,
        0.        , 0.        ],
       [0.5938157 , 0.28143902, 0.45827151, 0.38805451, 0.        ,
        0.70710678, 0.        ],
       [0.03711348, 0.21107926, 0.29300988, 0.29850347, 0.40824829,
        0.        , 0.        ],
       [0.29690785, 0.28143902, 0.28996826, 0.29850347, 0.40824829,
        0.        , 0.        ]])

In [51]:
df_norm = pd.DataFrame(norm_data, index=df_dummies.index, columns=df_dummies.columns)
df_norm

,Capacity,Ram,Weight,inch,OS_Android,OS_ios,OS_windows
Name,,,,,,,
Galaxy S10,0.296908,0.562878,0.330523,0.370144,0.408248,0.000000,0.0
Lumia 950,0.074227,0.211079,0.304163,0.310444,0.000000,0.000000,1.0
Xpreia 1 ll,0.593816,0.562878,0.367023,0.388055,0.408248,0.000000,0.0
iphone 7,0.296908,0.140720,0.279830,0.280593,0.000000,0.707107,0.0
U Ultra,0.148454,0.281439,0.344718,0.340294,0.408248,0.000000,0.0
Galaxy S5,0.037113,0.140720,0.294024,0.304474,0.408248,0.000000,0.0
iphone 11 pro max,0.593816,0.281439,0.458272,0.388055,0.000000,0.707107,0.0
Moto G5,0.037113,0.211079,0.293010,0.298503,0.408248,0.000000,0.0
Pixel,0.296908,0.281439,0.289968,0.298503,0.408248,0.000000,0.0

In [52]:
norm_data = normalize(df_dummies, norm='l1', axis=0)
norm_data

array([[0.125     , 0.21052632, 0.11160561, 0.1242485 , 0.16666667,
        0.        , 0.        ],
       [0.03125   , 0.07894737, 0.10270455, 0.10420842, 0.        ,
        0.        , 1.        ],
       [0.25      , 0.21052632, 0.12393016, 0.13026052, 0.16666667,
        0.        , 0.        ],
       [0.125     , 0.05263158, 0.09448819, 0.09418838, 0.        ,
        0.5       , 0.        ],
       [0.0625    , 0.10526316, 0.11639849, 0.11422846, 0.16666667,
        0.        , 0.        ],
       [0.015625  , 0.05263158, 0.09928107, 0.10220441, 0.16666667,
        0.        , 0.        ],
       [0.25      , 0.10526316, 0.15474153, 0.13026052, 0.        ,
        0.5       , 0.        ],
       [0.015625  , 0.07894737, 0.09893872, 0.1002004 , 0.16666667,
        0.        , 0.        ],
       [0.125     , 0.10526316, 0.09791167, 0.1002004 , 0.16666667,
        0.        , 0.        ]])

In [53]:
df_norm = pd.DataFrame(norm_data, index=df_dummies.index, columns=df_dummies.columns)
df_norm

,Capacity,Ram,Weight,inch,OS_Android,OS_ios,OS_windows
Name,,,,,,,
Galaxy S10,0.125000,0.210526,0.111606,0.124248,0.166667,0.0,0.0
Lumia 950,0.031250,0.078947,0.102705,0.104208,0.000000,0.0,1.0
Xpreia 1 ll,0.250000,0.210526,0.123930,0.130261,0.166667,0.0,0.0
iphone 7,0.125000,0.052632,0.094488,0.094188,0.000000,0.5,0.0
U Ultra,0.062500,0.105263,0.116398,0.114228,0.166667,0.0,0.0
Galaxy S5,0.015625,0.052632,0.099281,0.102204,0.166667,0.0,0.0
iphone 11 pro max,0.250000,0.105263,0.154742,0.130261,0.000000,0.5,0.0
Moto G5,0.015625,0.078947,0.098939,0.100200,0.166667,0.0,0.0
Pixel,0.125000,0.105263,0.097912,0.100200,0.166667,0.0,0.0

In [54]:
from sklearn.preprocessing import minmax_scale

In [56]:
minmax_data = minmax_scale(df_dummies, feature_range=(0, 1))
minmax_data

array([[0.46666667, 1.        , 0.28409091, 0.83333333, 1.        ,
        0.        , 0.        ],
       [0.06666667, 0.16666667, 0.13636364, 0.27777778, 0.        ,
        0.        , 1.        ],
       [1.        , 1.        , 0.48863636, 1.        , 1.        ,
        0.        , 0.        ],
       [0.46666667, 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.2       , 0.33333333, 0.36363636, 0.55555556, 1.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.07954545, 0.22222222, 1.        ,
        0.        , 0.        ],
       [1.        , 0.33333333, 1.        , 1.        , 0.        ,
        1.        , 0.        ],
       [0.        , 0.16666667, 0.07386364, 0.16666667, 1.        ,
        0.        , 0.        ],
       [0.46666667, 0.33333333, 0.05681818, 0.16666667, 1.        ,
        0.        , 0.        ]])

In [57]:
df_minmax = pd.DataFrame(minmax_data, index=df_dummies.index, columns=df_dummies.columns)
df_minmax

,Capacity,Ram,Weight,inch,OS_Android,OS_ios,OS_windows
Name,,,,,,,
Galaxy S10,0.466667,1.000000,0.284091,0.833333,1.0,0.0,0.0
Lumia 950,0.066667,0.166667,0.136364,0.277778,0.0,0.0,1.0
Xpreia 1 ll,1.000000,1.000000,0.488636,1.000000,1.0,0.0,0.0
iphone 7,0.466667,0.000000,0.000000,0.000000,0.0,1.0,0.0
U Ultra,0.200000,0.333333,0.363636,0.555556,1.0,0.0,0.0
Galaxy S5,0.000000,0.000000,0.079545,0.222222,1.0,0.0,0.0
iphone 11 pro max,1.000000,0.333333,1.000000,1.000000,0.0,1.0,0.0
Moto G5,0.000000,0.166667,0.073864,0.166667,1.0,0.0,0.0
Pixel,0.466667,0.333333,0.056818,0.166667,1.0,0.0,0.0