In [4]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import os

In [5]:
dataset = os.path.join('datasets', 'smartphones.csv')
df = pd.read_csv(dataset)
df

                Name        OS  Capacity  Ram  Weight    Company  inch
0         Galaxy S10   Android       128    8   163.0    Samsung   6.2
1          Lumia 950  windows         32    3   150.0  Microsoft   5.2
2        Xpreia 1 ll   Android       256    8   181.0       Sony   6.5
3          iphone 7        ios       128    2   138.0      Apple   4.7
4            U Ultra   Android        64    4   170.0        HTC   5.7
5          Galaxy S5   Android        16    2   145.0    Samsung   5.1
6  iphone 11 pro max       ios       256    4   226.0      Apple   6.5
7            Moto G5   Android        16    3   144.5   Motorola   5.0
8             Pixel    Android       128    4   143.0     Google   5.0

In [6]:
df.set_index('Name', inplace=True)
df

                         OS  Capacity  Ram  Weight    Company  inch
Name
Galaxy S10          Android       128    8   163.0    Samsung   6.2
Lumia 950          windows         32    3   150.0  Microsoft   5.2
Xpreia 1 ll         Android       256    8   181.0       Sony   6.5
iphone 7                ios       128    2   138.0      Apple   4.7
U Ultra             Android        64    4   170.0        HTC   5.7
Galaxy S5           Android        16    2   145.0    Samsung   5.1
iphone 11 pro max       ios       256    4   226.0      Apple   6.5
Moto G5             Android        16    3   144.5   Motorola   5.0
Pixel               Android       128    4   143.0     Google   5.0

In [8]:
df.drop('Company', axis=1, inplace=True)
df

                         OS  Capacity  Ram  Weight  inch
Name
Galaxy S10          Android       128    8   163.0   6.2
Lumia 950          windows         32    3   150.0   5.2
Xpreia 1 ll         Android       256    8   181.0   6.5
iphone 7                ios       128    2   138.0   4.7
U Ultra             Android        64    4   170.0   5.7
Galaxy S5           Android        16    2   145.0   5.1
iphone 11 pro max       ios       256    4   226.0   6.5
Moto G5             Android        16    3   144.5   5.0
Pixel               Android       128    4   143.0   5.0

In [9]:
df_dummies = pd.get_dummies(df)
df_dummies

,Capacity,Ram,Weight,inch,OS_Android,OS_ios,OS_windows
Name,,,,,,,
Galaxy S10,128,8,163.0,6.2,True,False,False
Lumia 950,32,3,150.0,5.2,False,False,True
Xpreia 1 ll,256,8,181.0,6.5,True,False,False
iphone 7,128,2,138.0,4.7,False,True,False
U Ultra,64,4,170.0,5.7,True,False,False
Galaxy S5,16,2,145.0,5.1,True,False,False
iphone 11 pro max,256,4,226.0,6.5,False,True,False
Moto G5,16,3,144.5,5.0,True,False,False
Pixel,128,4,143.0,5.0,True,False,False