In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import os

In [2]:
dataset = os.path.join('datasets', 'mydata.csv')
df = pd.read_csv(dataset)
df

   columns1 columns2 columns3
0         1        a        A
1         2        a        A
2         2        a        A
3         3        b        B
4         4        b        B
5         4        b        B

In [3]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [4]:
df.drop_duplicates()

   columns1 columns2 columns3
0         1        a        A
1         2        a        A
3         3        b        B
4         4        b        B

In [5]:
df.drop_duplicates(['columns2'])

   columns1 columns2 columns3
0         1        a        A
3         3        b        B

In [6]:
dataset = os.path.join('datasets', 'my_source1.csv')
df1 = pd.read_csv(dataset)
df1

       0  1   2   3   4
0  babak  1  13  17  17
1   raha  2  14  14  15
2   sara  3  17  12  20
3   reza  4  12  18  19

In [7]:
dataset = os.path.join('datasets', 'my_source2.csv')
df2 = pd.read_csv(dataset)
df2

        0  1   2   3
0   babak  1  13  17
1   baran  2  15  20
2    sara  3  14  19
3   arash  4  20  19
4  mehran  5  15  18
5    reza  6  14  12

In [8]:
my_concat = pd.concat([df1, df2], axis=0, ignore_index=True)
my_concat

        0  1   2   3     4
0   babak  1  13  17  17.0
1    raha  2  14  14  15.0
2    sara  3  17  12  20.0
3    reza  4  12  18  19.0
4   babak  1  13  17   NaN
5   baran  2  15  20   NaN
6    sara  3  14  19   NaN
7   arash  4  20  19   NaN
8  mehran  5  15  18   NaN
9    reza  6  14  12   NaN

In [9]:
my_concat.drop(['4'], axis=1, inplace=True)
my_concat

        0  1   2   3
0   babak  1  13  17
1    raha  2  14  14
2    sara  3  17  12
3    reza  4  12  18
4   babak  1  13  17
5   baran  2  15  20
6    sara  3  14  19
7   arash  4  20  19
8  mehran  5  15  18
9    reza  6  14  12

In [10]:
my_concat.drop_duplicates(inplace=True)
my_concat

        0  1   2   3
0   babak  1  13  17
1    raha  2  14  14
2    sara  3  17  12
3    reza  4  12  18
5   baran  2  15  20
6    sara  3  14  19
7   arash  4  20  19
8  mehran  5  15  18
9    reza  6  14  12