In [44]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import os

In [45]:
dataset = os.path.join('datasets', 'c_data.csv')
df = pd.read_csv(dataset, header=1)
df

,1,CountryName,CountryCode,Population growth,Total population,Area (sq. km)
0,2,Brazil,BRA,0.817555711,207652865,8358140
1,3,Switzerland,CHE,1.077221168,8372098,39516
2,4,Germany,DEU,1.193866758,82667685,348900
3,5,Denmark,DNK,0.834637611,?,42262
4,6,Spain,ESP,-0.008048086,46443959,500210
5,7,France,FRA,0.407491036,66896109,547557
6,8,Japan,JPN,-0.115284177,126994511,364560
7,9,Greece,GRC,-0.687542545,10746740,128900
8,10,Iran,IRN,1.1487886,80277428,1628760
9,11,Kuwait,KWT,2.924206194,4052584,?
10,12,Morocco,MAR,?,35276786,446300
11,13,Nigeria,NGA,2.619033526,185989640,910770
12,14,Qatar,QAT,3.495069918,2569804,11610
13,15,Sweden,SWE,?,9903122,407310
14,16,India,IND,1.148214693,1324171354,2973190
15,17,World,WLD,1.18167997,7442135578,129733172.7

In [46]:
df.rename(
    columns={
        "CountryName": "Name",
        "CountryCode": "Code",
        "Population growth": "Growth",
        "Total population": "Population",
        "Area (sq. km)": "Area",
    },
    inplace=True,
)
df

     1         Name Code        Growth  Population         Area
0    2       Brazil  BRA   0.817555711   207652865      8358140
1    3  Switzerland  CHE   1.077221168     8372098        39516
2    4      Germany  DEU   1.193866758    82667685       348900
3    5      Denmark  DNK   0.834637611           ?        42262
4    6        Spain  ESP  -0.008048086    46443959       500210
5    7       France  FRA   0.407491036    66896109       547557
6    8        Japan  JPN  -0.115284177   126994511       364560
7    9       Greece  GRC  -0.687542545    10746740       128900
8   10         Iran  IRN     1.1487886    80277428      1628760
9   11       Kuwait  KWT   2.924206194     4052584            ?
10  12      Morocco  MAR             ?    35276786       446300
11  13      Nigeria  NGA   2.619033526   185989640       910770
12  14        Qatar  QAT   3.495069918     2569804        11610
13  15       Sweden  SWE             ?     9903122       407310
14  16        India  IND   1.148214693  1324171354      2973190
15  17        World  WLD    1.18167997  7442135578  129733172.7

In [47]:
df.drop(['1', 'Code'], axis=1, inplace=True)
df

           Name        Growth  Population         Area
0        Brazil   0.817555711   207652865      8358140
1   Switzerland   1.077221168     8372098        39516
2       Germany   1.193866758    82667685       348900
3       Denmark   0.834637611           ?        42262
4         Spain  -0.008048086    46443959       500210
5        France   0.407491036    66896109       547557
6         Japan  -0.115284177   126994511       364560
7        Greece  -0.687542545    10746740       128900
8          Iran     1.1487886    80277428      1628760
9        Kuwait   2.924206194     4052584            ?
10      Morocco             ?    35276786       446300
11      Nigeria   2.619033526   185989640       910770
12        Qatar   3.495069918     2569804        11610
13       Sweden             ?     9903122       407310
14        India   1.148214693  1324171354      2973190
15        World    1.18167997  7442135578  129733172.7

In [48]:
df.set_index('Name', inplace=True)
df

                   Growth  Population         Area
Name
Brazil        0.817555711   207652865      8358140
Switzerland   1.077221168     8372098        39516
Germany       1.193866758    82667685       348900
Denmark       0.834637611           ?        42262
Spain        -0.008048086    46443959       500210
France        0.407491036    66896109       547557
Japan        -0.115284177   126994511       364560
Greece       -0.687542545    10746740       128900
Iran            1.1487886    80277428      1628760
Kuwait        2.924206194     4052584            ?
Morocco                 ?    35276786       446300
Nigeria       2.619033526   185989640       910770
Qatar         3.495069918     2569804        11610
Sweden                  ?     9903122       407310
India         1.148214693  1324171354      2973190
World          1.18167997  7442135578  129733172.7

In [49]:
df.replace('?', np.nan, inplace=True)
df

                   Growth  Population         Area
Name
Brazil        0.817555711   207652865      8358140
Switzerland   1.077221168     8372098        39516
Germany       1.193866758    82667685       348900
Denmark       0.834637611         NaN        42262
Spain        -0.008048086    46443959       500210
France        0.407491036    66896109       547557
Japan        -0.115284177   126994511       364560
Greece       -0.687542545    10746740       128900
Iran            1.1487886    80277428      1628760
Kuwait        2.924206194     4052584          NaN
Morocco               NaN    35276786       446300
Nigeria       2.619033526   185989640       910770
Qatar         3.495069918     2569804        11610
Sweden                NaN     9903122       407310
India         1.148214693  1324171354      2973190
World          1.18167997  7442135578  129733172.7

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, Brazil to World
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Growth      14 non-null     object
 1   Population  15 non-null     object
 2   Area        15 non-null     object
dtypes: object(3)
memory usage: 512.0+ bytes

In [51]:
df.dtypes

Growth        object
Population    object
Area          object
dtype: object

In [52]:
df

                   Growth  Population         Area
Name
Brazil        0.817555711   207652865      8358140
Switzerland   1.077221168     8372098        39516
Germany       1.193866758    82667685       348900
Denmark       0.834637611         NaN        42262
Spain        -0.008048086    46443959       500210
France        0.407491036    66896109       547557
Japan        -0.115284177   126994511       364560
Greece       -0.687542545    10746740       128900
Iran            1.1487886    80277428      1628760
Kuwait        2.924206194     4052584          NaN
Morocco               NaN    35276786       446300
Nigeria       2.619033526   185989640       910770
Qatar         3.495069918     2569804        11610
Sweden                NaN     9903122       407310
India         1.148214693  1324171354      2973190
World          1.18167997  7442135578  129733172.7

In [53]:
df['Area'] = [float(x) for x in df['Area']]
df['Growth'] = [float(x) for x in df['Growth']]
df['Population'] = [float(x) for x in df['Population']]
df

               Growth    Population         Area
Name
Brazil       0.817556  2.076529e+08    8358140.0
Switzerland  1.077221  8.372098e+06      39516.0
Germany      1.193867  8.266768e+07     348900.0
Denmark      0.834638           NaN      42262.0
Spain       -0.008048  4.644396e+07     500210.0
France       0.407491  6.689611e+07     547557.0
Japan       -0.115284  1.269945e+08     364560.0
Greece      -0.687543  1.074674e+07     128900.0
Iran         1.148789  8.027743e+07    1628760.0
Kuwait       2.924206  4.052584e+06          NaN
Morocco           NaN  3.527679e+07     446300.0
Nigeria      2.619034  1.859896e+08     910770.0
Qatar        3.495070  2.569804e+06      11610.0
Sweden            NaN  9.903122e+06     407310.0
India        1.148215  1.324171e+09    2973190.0
World        1.181680  7.442136e+09  129733172.7

In [54]:
df.dtypes

Growth        float64
Population    float64
Area          float64
dtype: object

In [55]:
df.describe()

          Growth    Population          Area
count  14.000000  1.500000e+01  1.500000e+01
mean    1.145492  6.422767e+08  9.762744e+06
std     1.173195  1.909868e+09  3.325701e+07
min    -0.687543  2.569804e+06  1.161000e+04
25%     0.510007  1.032493e+07  2.389000e+05
50%     1.112718  6.689611e+07  4.463000e+05
75%     1.190820  1.564921e+08  1.269765e+06
max     3.495070  7.442136e+09  1.297332e+08

In [56]:
max_pop = df['Population'].max()
df['Population'][df['Population'] == max_pop]

Name
World    7.442136e+09
Name: Population, dtype: float64

In [57]:
df.drop('World', axis=0, inplace=True)
df

               Growth    Population       Area
Name
Brazil       0.817556  2.076529e+08  8358140.0
Switzerland  1.077221  8.372098e+06    39516.0
Germany      1.193867  8.266768e+07   348900.0
Denmark      0.834638           NaN    42262.0
Spain       -0.008048  4.644396e+07   500210.0
France       0.407491  6.689611e+07   547557.0
Japan       -0.115284  1.269945e+08   364560.0
Greece      -0.687543  1.074674e+07   128900.0
Iran         1.148789  8.027743e+07  1628760.0
Kuwait       2.924206  4.052584e+06        NaN
Morocco           NaN  3.527679e+07   446300.0
Nigeria      2.619034  1.859896e+08   910770.0
Qatar        3.495070  2.569804e+06    11610.0
Sweden            NaN  9.903122e+06   407310.0
India        1.148215  1.324171e+09  2973190.0

In [58]:
df.isnull().sum()

Growth        2
Population    1
Area          1
dtype: int64

In [59]:
df.dropna()

               Growth    Population       Area
Name
Brazil       0.817556  2.076529e+08  8358140.0
Switzerland  1.077221  8.372098e+06    39516.0
Germany      1.193867  8.266768e+07   348900.0
Spain       -0.008048  4.644396e+07   500210.0
France       0.407491  6.689611e+07   547557.0
Japan       -0.115284  1.269945e+08   364560.0
Greece      -0.687543  1.074674e+07   128900.0
Iran         1.148789  8.027743e+07  1628760.0
Nigeria      2.619034  1.859896e+08   910770.0
Qatar        3.495070  2.569804e+06    11610.0
India        1.148215  1.324171e+09  2973190.0

In [60]:
df.fillna(0)

               Growth    Population       Area
Name
Brazil       0.817556  2.076529e+08  8358140.0
Switzerland  1.077221  8.372098e+06    39516.0
Germany      1.193867  8.266768e+07   348900.0
Denmark      0.834638  0.000000e+00    42262.0
Spain       -0.008048  4.644396e+07   500210.0
France       0.407491  6.689611e+07   547557.0
Japan       -0.115284  1.269945e+08   364560.0
Greece      -0.687543  1.074674e+07   128900.0
Iran         1.148789  8.027743e+07  1628760.0
Kuwait       2.924206  4.052584e+06        0.0
Morocco      0.000000  3.527679e+07   446300.0
Nigeria      2.619034  1.859896e+08   910770.0
Qatar        3.495070  2.569804e+06    11610.0
Sweden       0.000000  9.903122e+06   407310.0
India        1.148215  1.324171e+09  2973190.0

In [61]:
df.fillna({'Growth': 0, 'Population': df.Population.mean(), 'Area': df.Population.mean()})

               Growth    Population         Area
Name
Brazil       0.817556  2.076529e+08    8358140.0
Switzerland  1.077221  8.372098e+06      39516.0
Germany      1.193867  8.266768e+07     348900.0
Denmark      0.834638  1.565725e+08      42262.0
Spain       -0.008048  4.644396e+07     500210.0
France       0.407491  6.689611e+07     547557.0
Japan       -0.115284  1.269945e+08     364560.0
Greece      -0.687543  1.074674e+07     128900.0
Iran         1.148789  8.027743e+07    1628760.0
Kuwait       2.924206  4.052584e+06  156572477.5
Morocco      0.000000  3.527679e+07     446300.0
Nigeria      2.619034  1.859896e+08     910770.0
Qatar        3.495070  2.569804e+06      11610.0
Sweden       0.000000  9.903122e+06     407310.0
India        1.148215  1.324171e+09    2973190.0

In [62]:
df.ffill()

               Growth    Population       Area
Name
Brazil       0.817556  2.076529e+08  8358140.0
Switzerland  1.077221  8.372098e+06    39516.0
Germany      1.193867  8.266768e+07   348900.0
Denmark      0.834638  8.266768e+07    42262.0
Spain       -0.008048  4.644396e+07   500210.0
France       0.407491  6.689611e+07   547557.0
Japan       -0.115284  1.269945e+08   364560.0
Greece      -0.687543  1.074674e+07   128900.0
Iran         1.148789  8.027743e+07  1628760.0
Kuwait       2.924206  4.052584e+06  1628760.0
Morocco      2.924206  3.527679e+07   446300.0
Nigeria      2.619034  1.859896e+08   910770.0
Qatar        3.495070  2.569804e+06    11610.0
Sweden       3.495070  9.903122e+06   407310.0
India        1.148215  1.324171e+09  2973190.0

In [63]:
df.bfill()

               Growth    Population       Area
Name
Brazil       0.817556  2.076529e+08  8358140.0
Switzerland  1.077221  8.372098e+06    39516.0
Germany      1.193867  8.266768e+07   348900.0
Denmark      0.834638  4.644396e+07    42262.0
Spain       -0.008048  4.644396e+07   500210.0
France       0.407491  6.689611e+07   547557.0
Japan       -0.115284  1.269945e+08   364560.0
Greece      -0.687543  1.074674e+07   128900.0
Iran         1.148789  8.027743e+07  1628760.0
Kuwait       2.924206  4.052584e+06   446300.0
Morocco      2.619034  3.527679e+07   446300.0
Nigeria      2.619034  1.859896e+08   910770.0
Qatar        3.495070  2.569804e+06    11610.0
Sweden       1.148215  9.903122e+06   407310.0
India        1.148215  1.324171e+09  2973190.0

In [64]:
from sklearn.impute import SimpleImputer

In [65]:
i = SimpleImputer(missing_values=np.nan, strategy='mean')
i.fit(df)
new_df = i.transform(df)
new_df

array([[ 8.17555711e-01,  2.07652865e+08,  8.35814000e+06],
       [ 1.07722117e+00,  8.37209800e+06,  3.95160000e+04],
       [ 1.19386676e+00,  8.26676850e+07,  3.48900000e+05],
       [ 8.34637611e-01,  1.56572478e+08,  4.22620000e+04],
       [-8.04808600e-03,  4.64439590e+07,  5.00210000e+05],
       [ 4.07491036e-01,  6.68961090e+07,  5.47557000e+05],
       [-1.15284177e-01,  1.26994511e+08,  3.64560000e+05],
       [-6.87542545e-01,  1.07467400e+07,  1.28900000e+05],
       [ 1.14878860e+00,  8.02774280e+07,  1.62876000e+06],
       [ 2.92420619e+00,  4.05258400e+06,  1.19342750e+06],
       [ 1.14270849e+00,  3.52767860e+07,  4.46300000e+05],
       [ 2.61903353e+00,  1.85989640e+08,  9.10770000e+05],
       [ 3.49506992e+00,  2.56980400e+06,  1.16100000e+04],
       [ 1.14270849e+00,  9.90312200e+06,  4.07310000e+05],
       [ 1.14821469e+00,  1.32417135e+09,  2.97319000e+06]])

In [67]:
df[['Growth', 'Population', 'Area']] = new_df
df

               Growth    Population       Area
Name
Brazil       0.817556  2.076529e+08  8358140.0
Switzerland  1.077221  8.372098e+06    39516.0
Germany      1.193867  8.266768e+07   348900.0
Denmark      0.834638  1.565725e+08    42262.0
Spain       -0.008048  4.644396e+07   500210.0
France       0.407491  6.689611e+07   547557.0
Japan       -0.115284  1.269945e+08   364560.0
Greece      -0.687543  1.074674e+07   128900.0
Iran         1.148789  8.027743e+07  1628760.0
Kuwait       2.924206  4.052584e+06  1193427.5
Morocco      1.142708  3.527679e+07   446300.0
Nigeria      2.619034  1.859896e+08   910770.0
Qatar        3.495070  2.569804e+06    11610.0
Sweden       1.142708  9.903122e+06   407310.0
India        1.148215  1.324171e+09  2973190.0